name = "ingestion-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "hyperliquid_signals"
database_id = "<YOUR_D1_DATABASE_ID>"

[[queues.producers]]
binding = "SIGNAL_QUEUE"
queue = "signal-events"



